"use client";
import {useEffect,useMemo,useState} from "react";
import {LayoutDashboard,Users,Send,Search,Plus,X,Mail,CheckCircle2,MoreHorizontal,TrendingUp,Building2,RefreshCw} from "lucide-react";

type Status="Not contacted"|"LinkedIn sent"|"Email sent"|"Replied"|"Meeting"|"Not a fit";
type P={id:string;company:string;contact:string;title:string;email?:string;linkedin_url?:string;phone?:string;location:string;country?:string;employees:number;industry:string;tier:"Primary"|"Secondary";status:Status;notes?:string};
const statuses:Status[]=["Not contacted","LinkedIn sent","Email sent","Replied","Meeting","Not a fit"];
function normalize(x:any):P{return{id:String(x.id),company:x.company_name||"Unknown company",contact:x.contact_name||"Unknown contact",title:x.title||"Decision Maker",email:x.email||undefined,linkedin_url:x.linkedin_url||undefined,phone:x.phone||undefined,location:x.location||x.country||"—",country:x.country,employees:Number(x.employees)||0,industry:x.industry||"Logistics",tier:x.icp_tier==="Primary"?"Primary":"Secondary",status:statuses.includes(x.status)?x.status:"Not contacted",notes:x.notes||undefined}}
export default function Home(){const[tab,setTab]=useState("Overview"),[rows,setRows]=useState<P[]>([]),[q,setQ]=useState(""),[tier,setTier]=useState("All"),[sel,setSel]=useState<P|null>(null),[toast,setToast]=useState(""),[loading,setLoading]=useState(true),[lastSync,setLastSync]=useState<Date|null>(null);
 const load=async(silent=false)=>{try{if(!silent)setLoading(true);const r=await fetch("/api/prospects",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"CRM sync failed");setRows(j.map(normalize));setLastSync(new Date())}catch(e:any){setToast(e.message||"Unable to sync CRM")}finally{setLoading(false)}};
 useEffect(()=>{load();const timer=setInterval(()=>load(true),15000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),3000);return()=>clearTimeout(t)}},[toast]);
 const filtered=useMemo(()=>rows.filter(p=>(tier==="All"||p.tier===tier)&&`${p.contact} ${p.company} ${p.title} ${p.location} ${p.industry}`.toLowerCase().includes(q.toLowerCase())),[rows,q,tier]);
 const primary=rows.filter(p=>p.tier==="Primary").length,contacted=rows.filter(p=>p.status!=="Not contacted").length,replies=rows.filter(p=>p.status==="Replied"||p.status==="Meeting").length,companies=new Set(rows.map(p=>p.company.trim().toLowerCase())).size;
 const update=async(id:string,status:Status)=>{const before=rows;setRows(x=>x.map(p=>p.id===id?{...p,status}:p));setSel(x=>x&&x.id===id?{...x,status}:x);try{const r=await fetch("/api/prospects",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok)throw new Error("Could not save status");setToast(`Updated: ${status}`)}catch(e:any){setRows(before);setToast(e.message||"Could not save status")}};
 const groups=useMemo(()=>{const map=new Map<string,P[]>();filtered.forEach(p=>{const key=p.company.trim().toLowerCase();if(!map.has(key))map.set(key,[]);map.get(key)!.push(p)});return [...map.values()].sort((a,b)=>a[0].company.localeCompare(b[0].company))},[filtered]);
 return <main className="shell"><aside className="sidebar"><div className="brand"><b>S</b><span>SwiftLabor<small>Sales CRM</small></span></div><label>WORKSPACE</label>{[["Overview",LayoutDashboard],["Prospects",Users],["Outreach",Send]].map(([n,I]:any)=><button className={`nav ${tab===n?"on":""}`} onClick={()=>setTab(n)} key={n}><I size={17}/>{n}</button>)}<div className="sidefoot"><i/> CRM LIVE<small>North America · Logistics ICP</small></div></aside><section className="content"><header><div><small>SWIFTLABOR / OUTBOUND</small><h1>{tab}</h1></div><div className="headright"><span><i/> {loading?"Syncing":"Live workspace"}</span><button onClick={()=>load()}><RefreshCw size={16}/> Sync</button></div></header>
 {tab==="Overview"&&<><div className="hero"><div><label>NORTH AMERICA LOGISTICS ICP</label><h2>Your outbound command center.</h2><p>Decision makers, accounts and every outreach touch — organized in one place.</p></div><strong>{primary}<small>Primary ICP contacts</small></strong></div><div className="stats"><Stat a="Decision makers" b={rows.length} icon={<Users/>}/><Stat a="Target accounts" b={companies} icon={<Building2/>}/><Stat a="Contacted" b={contacted} icon={<Send/>}/><Stat a="Replies / meetings" b={replies} icon={<TrendingUp/>}/></div><Head title="Priority pipeline" sub="Primary accounts first. Log LinkedIn and email touches separately." action={()=>setTab("Prospects")}/><div className="card"><Table data={filtered.filter(p=>p.tier==="Primary").slice(0,10)} start={1} open={setSel} update={update}/></div></>}
 {tab==="Prospects"&&<><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search company, decision maker, title…"/></div><div className="seg">{["All","Primary","Secondary"].map(x=><button className={tier===x?"on":""} onClick={()=>setTier(x)} key={x}>{x}</button>)}</div></div><Head title={`${filtered.length} decision makers`} sub={`${companies} companies · grouped company-by-company · auto-sync every 15 seconds.`}/><div className="card"><GroupedTable groups={groups} open={setSel} update={update}/></div></>}
 {tab==="Outreach"&&<><div className="channels"><Channel icon={<Send/>} title="LinkedIn" n={rows.filter(p=>p.status==="LinkedIn sent").length} text="Connection requests / follow-ups"/><Channel icon={<Mail/>} title="Email" n={rows.filter(p=>p.status==="Email sent").length} text="Decision-maker emails"/><Channel icon={<CheckCircle2/>} title="Replies" n={replies} text="Positive conversations"/></div><Head title="Activity" sub={lastSync?`Last sync ${lastSync.toLocaleTimeString()}`:"Syncing…"}/><div className="card"><Table data={rows.filter(p=>p.status!=="Not contacted")} start={1} open={setSel} update={update}/></div></>}
 </section>{sel&&<div className="overlay" onClick={()=>setSel(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSel(null)}><X/></button><div className="bigavatar">{sel.contact.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><em className={sel.tier.toLowerCase()}>{sel.tier} ICP</em><h2>{sel.contact}</h2><p>{sel.title}</p><b>{sel.company}</b><div className="details"><div><small>LOCATION</small>{sel.location}</div><div><small>EMPLOYEES</small>{sel.employees}</div><div><small>INDUSTRY</small>{sel.industry}</div><div><small>EMAIL</small>{sel.email||"Not captured"}</div></div><label>OUTREACH STATUS</label><div className="statusgrid">{statuses.map(s=><button className={sel.status===s?"on":""} onClick={()=>update(sel.id,s)} key={s}>{s}</button>)}</div></div></div>}{toast&&<div className="toast">{toast}</div>}</main>}
function Stat({a,b,icon}:{a:string,b:number,icon:any}){return <div className="stat"><span>{icon}</span><small>{a}</small><b>{b}</b></div>}
function Head({title,sub,action}:{title:string,sub:string,action?:()=>void}){return <div className="sect"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={action}>Open prospects →</button>}</div>}
function Channel({icon,title,n,text}:{icon:any,title:string,n:number,text:string}){return <div className="channel"><span>{icon}</span><div><b>{title}</b><small>{text}</small></div><strong>{n}</strong></div>}
function Table({data,open,update,start=1}:{data:P[],open:(p:P)=>void,update:(id:string,s:Status)=>void,start?:number}){return <div className="table"><div className="th"><span># · DECISION MAKER</span><span>COMPANY</span><span>ICP</span><span>STATUS</span><span/></div>{data.map((p,i)=><div className="tr" key={p.id}><button className="person" onClick={()=>open(p)}><small className="rownum">{i+start}</small><i>{p.contact.split(" ").map(x=>x[0]).slice(0,2).join("")}</i><span><b>{p.contact}</b><small>{p.title}</small></span></button><button className="company" onClick={()=>open(p)}><b>{p.company}</b><small>{p.location} · {p.employees} employees</small></button><em className={p.tier.toLowerCase()}>{p.tier}</em><select value={p.status} onChange={e=>update(p.id,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="more" onClick={()=>open(p)}><MoreHorizontal size={17}/></button></div>)}</div>}
function GroupedTable({groups,open,update}:{groups:P[][],open:(p:P)=>void,update:(id:string,s:Status)=>void}){let n=0;return <div className="table"><div className="th"><span># · DECISION MAKER</span><span>COMPANY</span><span>ICP</span><span>STATUS</span><span/></div>{groups.map((g,gi)=><div key={g[0].company}><div className="companygroup"><span>{String(gi+1).padStart(2,"0")}</span><b>{g[0].company}</b><small>{g.length} decision maker{g.length===1?"":"s"} · {g[0].location} · {g[0].employees} employees</small></div>{g.map(p=><div className="tr" key={p.id}><button className="person" onClick={()=>open(p)}><small className="rownum">{++n}</small><i>{p.contact.split(" ").map(x=>x[0]).slice(0,2).join("")}</i><span><b>{p.contact}</b><small>{p.title}</small></span></button><button className="company" onClick={()=>open(p)}><b>{p.company}</b><small>{p.location} · {p.industry}</small></button><em className={p.tier.toLowerCase()}>{p.tier}</em><select value={p.status} onChange={e=>update(p.id,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="more" onClick={()=>open(p)}><MoreHorizontal size={17}/></button></div>)}</div>)}</div>}
